using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace {NAMESPACE_DOMAIN}
{
    /// <summary>
    /// Domain Class {CLASS_NAME_DOMAIN}
    /// </summary>
    /// <author>{AUTHOR_NAME}</author>
    /// <created>{CREATION_DATE}</created>
    /// <remarks>
    /// This code was generated by a tool.
    /// </remarks>
    public class {CLASS_NAME_DOMAIN}
    {
        /*-- BEGIN SECTION PROPERTIES */

        /*-- BEGIN SECTION INT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public int {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION INT */

        /*-- BEGIN SECTION BIGINT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public long {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION BIGINT */

        /*-- BEGIN SECTION SMALLINT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public short {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION SMALLINT */

        /*-- BEGIN SECTION TINYINT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public short {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION TINYINT */

        /*-- BEGIN SECTION DECIMAL AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public decimal {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION DECIMAL */

        /*-- BEGIN SECTION REAL AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public float {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION REAL */

        /*-- BEGIN SECTION FLOAT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public float {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION FLOAT */

        /*-- BEGIN SECTION DOUBLE AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public double {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION DOUBLE */

        /*-- BEGIN SECTION MONEY AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public decimal {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION MONEY */

        /*-- BEGIN SECTION CHAR AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public string {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION CHAR */

        /*-- BEGIN SECTION NCHAR AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public string {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION NCHAR */

        /*-- BEGIN SECTION VARCHAR AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public string {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION VARCHAR */

        /*-- BEGIN SECTION NVARCHAR AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public string {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION NVARCHAR */

        /*-- BEGIN SECTION TEXT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public string {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION TEXT */

        /*-- BEGIN SECTION NTEXT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public string {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION NTEXT */

        /*-- BEGIN SECTION MEDIUMTEXT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public string {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION MEDIUMTEXT */

        /*-- BEGIN SECTION LONGTEXT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public string {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION LONGTEXT */

        /*-- BEGIN SECTION ENUM AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public string {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION ENUM */

        /*-- BEGIN SECTION BIT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public bool {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION BIT */

        /*-- BEGIN SECTION SMALLDATETIME AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public DateTime {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION SMALLDATETIME */

        /*-- BEGIN SECTION DATETIME AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public DateTime {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION DATETIME */

        /*-- BEGIN SECTION DATE AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public DateTime {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION DATE */

        /*-- BEGIN SECTION TIME AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public TimeSpan {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION TIME */

        /*-- BEGIN SECTION BLOB AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public object {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION BLOB */

        /*-- BEGIN SECTION LONGBLOB AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public object {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION LONGBLOB */

        /*-- BEGIN SECTION IMAGE AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        public byte[] {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION IMAGE */

        /*-- END SECTION PROPERTIES */

        /// <summary>
        /// Initializes a new instance of the <see cref="{CLASS_NAME_DOMAIN}"/> class.
        /// </summary>
        public {CLASS_NAME_DOMAIN}()
        {
            /*-- BEGIN SECTION PARAMETERS */
            /*-- BEGIN SECTION INT AS VAR */{VAR.PROPERTYNAME} = 0;
            /*-- END SECTION INT */
            /*-- BEGIN SECTION BIGINT AS VAR */{VAR.PROPERTYNAME} = 0;
            /*-- END SECTION BIGINT */
            /*-- BEGIN SECTION SMALLINT AS VAR */{VAR.PROPERTYNAME} = 0;
            /*-- END SECTION SMALLINT */
            /*-- BEGIN SECTION TINYINT AS VAR */{VAR.PROPERTYNAME} = 0;
            /*-- END SECTION TINYINT */
            /*-- BEGIN SECTION DECIMAL AS VAR */{VAR.PROPERTYNAME} = 0;
            /*-- END SECTION DECIMAL */
            /*-- BEGIN SECTION REAL AS VAR */{VAR.PROPERTYNAME} = 0.0f;
            /*-- END SECTION REAL */
            /*-- BEGIN SECTION FLOAT AS VAR */{VAR.PROPERTYNAME} = 0.0f;
            /*-- END SECTION FLOAT */
            /*-- BEGIN SECTION DOUBLE AS VAR */{VAR.PROPERTYNAME} = 0;
            /*-- END SECTION DOUBLE */
            /*-- BEGIN SECTION MONEY AS VAR */{VAR.PROPERTYNAME} = 0;
            /*-- END SECTION MONEY */
            /*-- BEGIN SECTION CHAR AS VAR */{VAR.PROPERTYNAME} = string.Empty;
            /*-- END SECTION CHAR */
            /*-- BEGIN SECTION NCHAR AS VAR */{VAR.PROPERTYNAME} = string.Empty;
            /*-- END SECTION NCHAR */
            /*-- BEGIN SECTION VARCHAR AS VAR */{VAR.PROPERTYNAME} = string.Empty;
            /*-- END SECTION VARCHAR */
            /*-- BEGIN SECTION NVARCHAR AS VAR */{VAR.PROPERTYNAME} = string.Empty;
            /*-- END SECTION NVARCHAR */
            /*-- BEGIN SECTION TEXT AS VAR */{VAR.PROPERTYNAME} = string.Empty;
            /*-- END SECTION TEXT */
            /*-- BEGIN SECTION NTEXT AS VAR */{VAR.PROPERTYNAME} = string.Empty;
            /*-- END SECTION NTEXT */
            /*-- BEGIN SECTION MEDIUMTEXT AS VAR */{VAR.PROPERTYNAME} = string.Empty;
            /*-- END SECTION MEDIUMTEXT */
            /*-- BEGIN SECTION LONGTEXT AS VAR */{VAR.PROPERTYNAME} = string.Empty;
            /*-- END SECTION LONGTEXT */
            /*-- BEGIN SECTION ENUM AS VAR */{VAR.PROPERTYNAME} = string.Empty;
            /*-- END SECTION ENUM */
            /*-- BEGIN SECTION BIT AS VAR */{VAR.PROPERTYNAME} = false;
            /*-- END SECTION BIT */
            /*-- BEGIN SECTION SMALLDATETIME AS VAR */{VAR.PROPERTYNAME} = new DateTime(1900, 1, 1);
            /*-- END SECTION SMALLDATETIME */
            /*-- BEGIN SECTION DATETIME AS VAR */{VAR.PROPERTYNAME} = new DateTime(1900, 1, 1);
            /*-- END SECTION DATETIME */
            /*-- BEGIN SECTION DATE AS VAR */{VAR.PROPERTYNAME} = new DateTime(1900, 1, 1);
            /*-- END SECTION DATE */
            /*-- BEGIN SECTION TIME AS VAR */{VAR.PROPERTYNAME} = new TimeSpan(0);
            /*-- END SECTION TIME */
            /*-- BEGIN SECTION BLOB AS VAR */{VAR.PROPERTYNAME} = null;
            /*-- END SECTION BLOB */
            /*-- BEGIN SECTION LONGBLOB AS VAR */{VAR.PROPERTYNAME} = null;
            /*-- END SECTION LONGBLOB */
            /*-- BEGIN SECTION IMAGE AS VAR */{VAR.PROPERTYNAME} = null;
            /*-- END SECTION IMAGE */
            /*-- END SECTION PARAMETERS */
        }
    }
}
