using System;
using System.Xml;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace {NAMESPACE_MODEL}
{
    /// <summary>
    /// Model Class {CLASS_NAME_MODEL}
    /// </summary>
    /// <author>{AUTHOR_NAME}</author>
    /// <created>{CREATION_DATE}</created>
    /// <remarks>
    /// This code was generated by a tool.
    /// </remarks>
    public class {CLASS_NAME_MODEL}
    {
        /*-- BEGIN SECTION PROPERTIES */

        /*-- BEGIN SECTION BIGINT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
		[Display(Name = "{VAR.PROPERTYNAME}")]
        public long {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION BIGINT */

        /*-- BEGIN SECTION BINARY AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
		[Display(Name = "{VAR.PROPERTYNAME}")]
        public byte[] {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION BINARY */

        /*-- BEGIN SECTION BIT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public bool {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION BIT */

        /*-- BEGIN SECTION CHAR AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public char[] {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION CHAR */

        /*-- BEGIN SECTION DATETIME AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public DateTime {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION DATETIME */

        /*-- BEGIN SECTION DECIMAL AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public decimal {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION DECIMAL */

        /*-- BEGIN SECTION FLOAT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public double {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION FLOAT */

        /*-- BEGIN SECTION IMAGE AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public byte[] {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION IMAGE */

        /*-- BEGIN SECTION INT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public int {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION INT */

        /*-- BEGIN SECTION MONEY AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public decimal {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION MONEY */

        /*-- BEGIN SECTION NCHAR AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public char[] {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION NCHAR */

        /*-- BEGIN SECTION NTEXT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public string {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION NTEXT */

        /*-- BEGIN SECTION NVARCHAR AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public string {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION NVARCHAR */

        /*-- BEGIN SECTION REAL AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public float {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION REAL */

        /*-- BEGIN SECTION UNIQUEIDENTIFIER AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public Guid {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION UNIQUEIDENTIFIER */

        /*-- BEGIN SECTION SMALLDATETIME AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public DateTime {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION SMALLDATETIME */

        /*-- BEGIN SECTION SMALLINT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public short {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION SMALLINT */

        /*-- BEGIN SECTION SMALLMONEY AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public decimal {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION SMALLMONEY */

        /*-- BEGIN SECTION TEXT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public string {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION TEXT */

        /*-- BEGIN SECTION TIMESTAMP AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public byte[] {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION TIMESTAMP */

        /*-- BEGIN SECTION TINYINT AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public byte {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION TINYINT */

        /*-- BEGIN SECTION VARBINARY AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public byte[] {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION VARBINARY */

        /*-- BEGIN SECTION VARCHAR AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public string {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION VARCHAR */

        /*-- BEGIN SECTION XML AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public XmlDocument  {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION XML */

        /*-- BEGIN SECTION DATE AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public DateTime {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION DATE */

        /*-- BEGIN SECTION TIME AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public TimeSpan {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION TIME */

        /*-- BEGIN SECTION DATETIME2 AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public DateTime {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION DATETIME2 */

        /*-- BEGIN SECTION DATETIMEOFFSET AS VAR */
        /// <summary>
        /// {VAR.PROPERTYNAME}
        /// </summary>
        [Display(Name = "{VAR.PROPERTYNAME}")]
        public DateTimeOffset {VAR.PROPERTYNAME} { get; set; }
        /*-- END SECTION DATETIMEOFFSET */

        /*-- END SECTION PROPERTIES */

        /// <summary>
        /// Initializes a new instance of the <see cref="{CLASS_NAME_MODEL}"/> class.
        /// </summary>
        public {CLASS_NAME_MODEL}()
        {
            /*-- BEGIN SECTION PARAMETERS */
            /*-- BEGIN SECTION BIGINT AS VAR */{VAR.PROPERTYNAME} = 0;
            /*-- END SECTION BIGINT */
            /*-- BEGIN SECTION BINARY AS VAR */{VAR.PROPERTYNAME} = null;
            /*-- END SECTION BINARY */
            /*-- BEGIN SECTION BIT AS VAR */{VAR.PROPERTYNAME} = false;
            /*-- END SECTION BIT */
            /*-- BEGIN SECTION CHAR AS VAR */{VAR.PROPERTYNAME} = null;
            /*-- END SECTION CHAR */
            /*-- BEGIN SECTION DATETIME AS VAR */{VAR.PROPERTYNAME} = new DateTime();
            /*-- END SECTION DATETIME */
            /*-- BEGIN SECTION DECIMAL AS VAR */{VAR.PROPERTYNAME} = 0;
            /*-- END SECTION DECIMAL */
            /*-- BEGIN SECTION FLOAT AS VAR */{VAR.PROPERTYNAME} = 0.0f;
            /*-- END SECTION FLOAT */
            /*-- BEGIN SECTION IMAGE AS VAR */{VAR.PROPERTYNAME} = null;
            /*-- END SECTION IMAGE */
            /*-- BEGIN SECTION INT AS VAR */{VAR.PROPERTYNAME} = 0;
            /*-- END SECTION INT */
            /*-- BEGIN SECTION MONEY AS VAR */{VAR.PROPERTYNAME} = 0;
            /*-- END SECTION MONEY */
            /*-- BEGIN SECTION NCHAR AS VAR */{VAR.PROPERTYNAME} = null;
            /*-- END SECTION NCHAR */
            /*-- BEGIN SECTION NTEXT AS VAR */{VAR.PROPERTYNAME} = string.Empty;
            /*-- END SECTION NTEXT */
            /*-- BEGIN SECTION NVARCHAR AS VAR */{VAR.PROPERTYNAME} = string.Empty;
            /*-- END SECTION NVARCHAR */
            /*-- BEGIN SECTION REAL AS VAR */{VAR.PROPERTYNAME} = 0.0f;
            /*-- END SECTION REAL */
            /*-- BEGIN SECTION UNIQUEIDENTIFIER AS VAR */{VAR.PROPERTYNAME} = new Guid();
            /*-- END SECTION UNIQUEIDENTIFIER */
            /*-- BEGIN SECTION SMALLDATETIME AS VAR */{VAR.PROPERTYNAME} = new DateTime();
            /*-- END SECTION SMALLDATETIME */
            /*-- BEGIN SECTION SMALLINT AS VAR */{VAR.PROPERTYNAME} = 0;
            /*-- END SECTION SMALLINT */
            /*-- BEGIN SECTION SMALLMONEY AS VAR */{VAR.PROPERTYNAME} = 0;
            /*-- END SECTION SMALLMONEY */
            /*-- BEGIN SECTION TEXT AS VAR */{VAR.PROPERTYNAME} = string.Empty;
            /*-- END SECTION TEXT */
            /*-- BEGIN SECTION TIMESTAMP AS VAR */{VAR.PROPERTYNAME} = null;
            /*-- END SECTION TIMESTAMP */
            /*-- BEGIN SECTION TINYINT AS VAR */{VAR.PROPERTYNAME} = 0;
            /*-- END SECTION TINYINT */
            /*-- BEGIN SECTION VARBINARY AS VAR */{VAR.PROPERTYNAME} = null;
            /*-- END SECTION VARBINARY */
            /*-- BEGIN SECTION VARCHAR AS VAR */{VAR.PROPERTYNAME} = string.Empty;
            /*-- END SECTION VARCHAR */
            /*-- BEGIN SECTION VARIANT AS VAR */{VAR.PROPERTYNAME} = string.Empty;
            /*-- END SECTION VARIANT */
            /*-- BEGIN SECTION XML AS VAR */{VAR.PROPERTYNAME} = null;
            /*-- END SECTION XML */
            /*-- BEGIN SECTION DATE AS VAR */{VAR.PROPERTYNAME} = new DateTime();
            /*-- END SECTION DATE */
            /*-- BEGIN SECTION TIME AS VAR */{VAR.PROPERTYNAME} = new TimeSpan(0);
            /*-- END SECTION TIME */
            /*-- BEGIN SECTION DATETIME2 AS VAR */{VAR.PROPERTYNAME} = new DateTime();
            /*-- END SECTION DATETIME2 */
            /*-- BEGIN SECTION DATETIMEOFFSET AS VAR */{VAR.PROPERTYNAME} = new DateTimeOffset();
            /*-- END SECTION DATETIMEOFFSET */
            /*-- END SECTION PARAMETERS */
        }
    }
}
