using System;
using System.Collections.Generic;
using System.Data;
using {NAMESPACE_DOMAIN};
using {NAMESPACE_DBHELPER};
using {NAMESPACE_ACCESS_MODEL};

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace {NAMESPACE_DATAACCESS}
{
    /// <summary>
    /// DataAccess Class {CLASS_NAME_DATAACCESS}
    /// </summary>
    /// <author>{AUTHOR_NAME}</author>
    /// <created>{CREATION_DATE}</created>
    /// <remarks>
    /// This class was generated by a tool.
    /// </remarks>
    public static class {CLASS_NAME_DATAACCESS}
    {
        #region base methods

        /// <summary>
        /// Save Entity <see cref="{CLASS_NAME_DOMAIN}"/> into Database
        /// </summary>
        /// <author>{AUTHOR_NAME}</author>
        /// <created>{CREATION_DATE}</created>
        /// <param name="{INSTANCE_NAME_DOMAIN}">Reference to <see cref="{CLASS_NAME_DOMAIN}"/>.</param>
        /// <returns>Entity PrimaryKey</returns>
        public static {PRIMARYKEY_DATATYPE} {SAVE_METHODNAME}({CLASS_NAME_DOMAIN} {INSTANCE_NAME_DOMAIN})
        {
            ParameterCollection parameters = new ParameterCollection
            {
                /*-- BEGIN SECTION PARAMETERS */
                /*-- BEGIN SECTION INT AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION INT */
                /*-- BEGIN SECTION BIGINT AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION BIGINT */
                /*-- BEGIN SECTION SMALLINT AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION SMALLINT */
                /*-- BEGIN SECTION TINYINT AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION TINYINT */
                /*-- BEGIN SECTION DECIMAL AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION DECIMAL */
                /*-- BEGIN SECTION REAL AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION REAL */
                /*-- BEGIN SECTION FLOAT AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION FLOAT */
                /*-- BEGIN SECTION DOUBLE AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION DOUBLE */
                /*-- BEGIN SECTION CHAR AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION CHAR */
                /*-- BEGIN SECTION VARCHAR AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION VARCHAR */
                /*-- BEGIN SECTION TEXT AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION TEXT */
                /*-- BEGIN SECTION MEDIUMTEXT AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION MEDIUMTEXT */
                /*-- BEGIN SECTION LONGTEXT AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION LONGTEXT */
                /*-- BEGIN SECTION ENUM AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION ENUM */
                /*-- BEGIN SECTION BIT AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION BIT */
                /*-- BEGIN SECTION SMALLDATETIME AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION SMALLDATETIME */
                /*-- BEGIN SECTION DATETIME AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION DATETIME */
                /*-- BEGIN SECTION DATE AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION DATE */
                /*-- BEGIN SECTION TIME AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION TIME */
                /*-- BEGIN SECTION BLOB AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION BLOB */
                /*-- BEGIN SECTION LONGBLOB AS VAR */new Parameter("{VAR.PARAMETERNAME}", {INSTANCE_NAME_DOMAIN}.{VAR.PROPERTYNAME}),
                /*-- END SECTION LONGBLOB */
                /*-- END SECTION PARAMETERS */
            };

            return {DBHELPER_INSTANCEOBJECT}.{GETSCALAR_METHODNAME}<{PRIMARYKEY_DATATYPE}>("{SAVE_STORED_PROCEDURE}", parameters);
        }

        /// <summary>
        /// Get a <see cref="{CLASS_NAME_DOMAIN}"/> entity from Database by Primary Key ID
        /// </summary>
        /// <author>{AUTOR_CLASE}</author>
        /// <created>{CREATION_DATE}</created>
        /// <param name="{PRIMARYKEY_LOCAL_VARIABLE}">ID de {CLASS_NAME_DOMAIN}.</param>
        /// <returns>Reference to a new instance of <see cref="{CLASS_NAME_DOMAIN}"/>.</returns>
        public static {CLASS_NAME_DOMAIN} {GETBYID_METHODNAME}({PRIMARYKEY_DATATYPE} {PRIMARYKEY_LOCAL_VARIABLE})
        {
            Parameter parameter = new Parameter("{PRIMARYKEY_PARAMETERNAME}", {PRIMARYKEY_LOCAL_VARIABLE});

            return {DBHELPER_INSTANCEOBJECT}.{GETENTITY_METHODNAME}("{GETBYID_STORED_PROCEDURE}", parameter, {BUILDFUNCTION_METHODNAME});
        }

        /// <summary>
        /// List all Entities from Database
        /// </summary>
        /// <author>{AUTOR_CLASE}</author>
        /// <created>{CREATION_DATE}</created>
        /// <returns><see cref="DataTable"/> con todos los objetos.</returns>
        public static DataTable {LISTALL_METHODNAME}()
        {
            return {DBHELPER_INSTANCEOBJECT}.{GETDATATABLE_METHODNAME}("{LISTALL_STORED_PROCEDURE}");
        }

        /// <summary>
        /// Delete a Entity from Database
        /// </summary>
        /// <author>{AUTOR_CLASE}</author>
        /// <created>{CREATION_DATE}</created>
        /// <param name="{PRIMARYKEY_LOCAL_VARIABLE}">ID de {CLASS_NAME_DOMAIN}.</param>
        /// <returns>Referencia a una clase <see cref="{CLASS_NAME_DOMAIN}"/>.</returns>
        public static void {DELETE_METHODNAME}({PRIMARYKEY_DATATYPE} {PRIMARYKEY_LOCAL_VARIABLE})
        {
            Parameter parameter = new Parameter("{PRIMARYKEY_PARAMETERNAME}", {PRIMARYKEY_LOCAL_VARIABLE});

            return {DBHELPER_INSTANCEOBJECT}.{EXECUTESP_METHODNAME}("{DELETE_STORED_PROCEDURE}", parameter);
        }

        #endregion

        #region aditional methods
        #endregion

        #region builder
        private static {CLASS_NAME_DOMAIN} {BUILDFUNCTION_METHODNAME}(IDataReader row)
        {
            return new {CLASS_NAME_DOMAIN}
            {
                /*-- BEGIN SECTION PROPERTIES */
                /*-- BEGIN SECTION INT AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? Convert.ToInt32(row["{VAR.PROPERTYNAME}"]) : 0,
                /*-- END SECTION INT */
                /*-- BEGIN SECTION BIGINT AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? Convert.ToInt64(row["{VAR.PROPERTYNAME}"]) : 0,
                /*-- END SECTION BIGINT */
                /*-- BEGIN SECTION SMALLINT AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? Convert.ToInt16(row["{VAR.PROPERTYNAME}"]) : (short)0,
                /*-- END SECTION SMALLINT */
                /*-- BEGIN SECTION TINYINT AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? Convert.ToInt16(row["{VAR.PROPERTYNAME}"]) : (short)0,
                /*-- END SECTION TINYINT */
                /*-- BEGIN SECTION DECIMAL AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? Convert.ToDecimal(row["{VAR.PROPERTYNAME}"]) : 0,
                /*-- END SECTION DECIMAL */
                /*-- BEGIN SECTION REAL AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? Convert.ToFloat(row["{VAR.PROPERTYNAME}"]) : 0.0f,
                /*-- END SECTION REAL */
                /*-- BEGIN SECTION FLOAT AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? Convert.ToFloat(row["{VAR.PROPERTYNAME}"]) : 0.0f,
                /*-- END SECTION FLOAT */
                /*-- BEGIN SECTION DOUBLE AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? Convert.ToDouble(row["{VAR.PROPERTYNAME}"]) : 0,
                /*-- END SECTION DOUBLE */
                /*-- BEGIN SECTION CHAR AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? row["{VAR.PROPERTYNAME}"].ToString() : string.Empty,
                /*-- END SECTION CHAR */
                /*-- BEGIN SECTION VARCHAR AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? row["{VAR.PROPERTYNAME}"].ToString() : string.Empty,
                /*-- END SECTION VARCHAR */
                /*-- BEGIN SECTION TEXT AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? row["{VAR.PROPERTYNAME}"].ToString() : string.Empty,
                /*-- END SECTION TEXT */
                /*-- BEGIN SECTION MEDIUMTEXT AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? row["{VAR.PROPERTYNAME}"].ToString() : string.Empty,
                /*-- END SECTION MEDIUMTEXT */
                /*-- BEGIN SECTION LONGTEXT AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? row["{VAR.PROPERTYNAME}"].ToString() : string.Empty,
                /*-- END SECTION LONGTEXT */
                /*-- BEGIN SECTION ENUM AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? row["{VAR.PROPERTYNAME}"].ToString() : string.Empty,
                /*-- END SECTION ENUM */
                /*-- BEGIN SECTION BIT AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value && Convert.ToBoolean(row["{VAR.PROPERTYNAME}"]),
                /*-- END SECTION BIT */
                /*-- BEGIN SECTION SMALLDATETIME AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? Convert.ToDateTime(row["{VAR.PROPERTYNAME}"]) : new DateTime(1900, 1, 1),
                /*-- END SECTION SMALLDATETIME */
                /*-- BEGIN SECTION DATETIME AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? Convert.ToDateTime(row["{VAR.PROPERTYNAME}"]) : new DateTime(1900, 1, 1),
                /*-- END SECTION DATETIME */
                /*-- BEGIN SECTION DATE AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? Convert.ToDateTime(row["{VAR.PROPERTYNAME}"]) : new DateTime(1900, 1, 1),
                /*-- END SECTION DATE */
                /*-- BEGIN SECTION TIME AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? TimeSpan.Parse(Convert.ToDateTime(row["{VAR.PROPERTYNAME}"]).ToLongTimeString()) : new TimeSpan(0),
                /*-- END SECTION TIME */
                /*-- BEGIN SECTION BLOB AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? row["{VAR.PROPERTYNAME}"] : null,
                /*-- END SECTION BLOB */
                /*-- BEGIN SECTION LONGBLOB AS VAR */{VAR.PROPERTYNAME} = row["{VAR.PROPERTYNAME}"] != DBNull.Value ? row["{VAR.PROPERTYNAME}"] : null,
                /*-- END SECTION LONGBLOB */
                /*-- END SECTION PROPERTIES */
            };
        }
        #endregion
    }
}
