//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_on {
            get {
                object obj = ResourceManager.GetObject("add_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_form_add {
            get {
                object obj = ResourceManager.GetObject("application_form_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Threading.Tasks;
        ///using Microsoft.AspNetCore.Mvc;
        ///using Microsoft.AspNetCore.Mvc.Rendering;
        ///using Microsoft.EntityFrameworkCore;
        ///using {NAMESPACE_DBCONTEXT};
        ///using {NAMESPACE_MODELS};
        ///
        ///namespace {NAMESPACE_CONTROLLER}
        ///{
        ///    public class {CLASS_NAME_CONTROLLER} : Controller
        ///    {
        ///        private readonly {DBCONTEXT_NAME} _context;
        ///
        ///        public {CLASS_NAME_CONTROLLER}({DBCONTEXT_NAME} context)
        ///        {
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string class_Controller {
            get {
                return ResourceManager.GetString("class_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Configuration;
        ///using System.Data;
        ///using System.Data.SqlClient;
        ///using System.Xml;
        ///using {NAMESPACE_DOMAIN};
        ///
        /////------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////-------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string class_DataAccess {
            get {
                return ResourceManager.GetString("class_DataAccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Configuration;
        ///using System.Data;
        ///using System.Data.SqlClient;
        ///using System.Xml;
        ///using {NAMESPACE_DOMAIN};
        ///
        /////------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////-------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string class_DataAccess_en
        {
            get
            {
                return ResourceManager.GetString("class_DataAccess_en", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Configuration;
        ///using System.Data;
        ///using System.Data.SqlClient;
        ///using System.Xml;
        ///using {NAMESPACE_DOMAIN};
        ///
        /////------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////-------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string class_DataAccess_es
        {
            get
            {
                return ResourceManager.GetString("class_DataAccess_es", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Xml;
        ///
        /////------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace {NAMESPACE_DOMAIN}
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Domain Class {CLASS_NAME_DOMAIN}
        ///    /// &lt;/summa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string class_Domain {
            get {
                return ResourceManager.GetString("class_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Xml;
        ///
        /////------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace {NAMESPACE_MODELS}
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Model Class {CLASS_NAME_MODEL}
        ///    /// &lt;/summary [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string class_Model {
            get {
                return ResourceManager.GetString("class_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cog {
            get {
                object obj = ResourceManager.GetObject("cog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_add {
            get {
                object obj = ResourceManager.GetObject("database_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.frostdisk.com/.
        /// </summary>
        internal static string DefaultAuthorWebsiteUrl {
            get {
                return ResourceManager.GetString("DefaultAuthorWebsiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrostDisk.
        /// </summary>
        internal static string DefaultCreatedBy {
            get {
                return ResourceManager.GetString("DefaultCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DefaultReleaseNotesUrl {
            get {
                return ResourceManager.GetString("DefaultReleaseNotesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diskette {
            get {
                object obj = ResourceManager.GetObject("diskette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap door_in {
            get {
                object obj = ResourceManager.GetObject("door_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _N&gt;Tx&apos;}rxm@a]Lg\z]dN3DBPNb(xwsMOgX2YVi&quot;Ktg*n-At&amp;u8&lt;rh&gt;Hlhs&quot;;;&amp;w.
        /// </summary>
        internal static string EncriptionKey {
            get {
                return ResourceManager.GetString("EncriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FrostDisk_about {
            get {
                object obj = ResourceManager.GetObject("FrostDisk_about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap interface_preferences {
            get {
                object obj = ResourceManager.GetObject("interface_preferences", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///                    GNU GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The GNU General Public License is a free, copyleft license for
        ///software and other kinds of works.
        ///
        ///  The licenses for most software and other practical works are designed
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
        ///
        ///You should have received a copy  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string license_about {
            get {
                return ResourceManager.GetString("license_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_white_add {
            get {
                object obj = ResourceManager.GetObject("page_white_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_white_c {
            get {
                object obj = ResourceManager.GetObject("page_white_c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_white_code {
            get {
                object obj = ResourceManager.GetObject("page_white_code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_white_cplusplus {
            get {
                object obj = ResourceManager.GetObject("page_white_cplusplus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_white_csharp {
            get {
                object obj = ResourceManager.GetObject("page_white_csharp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_white_database {
            get {
                object obj = ResourceManager.GetObject("page_white_database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_white_edit {
            get {
                object obj = ResourceManager.GetObject("page_white_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_white_php {
            get {
                object obj = ResourceManager.GetObject("page_white_php", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste_plain {
            get {
                object obj = ResourceManager.GetObject("paste_plain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_as {
            get {
                object obj = ResourceManager.GetObject("save_as", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_data {
            get {
                object obj = ResourceManager.GetObject("save_data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINT N&apos;Stored Procedure [dbo].[{DELETE_STORED_PROCEDURE}]&apos;
        ///GO
        ///IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[{DELETE_STORED_PROCEDURE}]&apos;) AND TYPE IN (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[{DELETE_STORED_PROCEDURE}]  
        ///GO
        ///CREATE PROCEDURE [dbo].[{DELETE_STORED_PROCEDURE}]
        ///(
        ///    @{PRIMARYKEY_PARAMETERNAME} {PRIMARYKEY_DATATYPE}
        ///)
        ///AS
        ///-- =============================================
        ///-- Author         : {AUTHOR_NAME}
        ///-- Creation Date  : {CREATION_DATE}
        ///-- Main Entity    : { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sp_Delete {
            get {
                return ResourceManager.GetString("sp_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINT N&apos;Stored Procedure [dbo].[{GETBYID_STORED_PROCEDURE}]&apos;
        ///GO
        ///IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[{GETBYID_STORED_PROCEDURE}]&apos;) AND TYPE IN (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[{GETBYID_STORED_PROCEDURE}]  
        ///GO
        ///CREATE PROCEDURE [dbo].[{GETBYID_STORED_PROCEDURE}]
        ///(
        ///    @{PRIMARYKEY_PARAMETERNAME} {PRIMARYKEY_DATATYPE}
        ///)
        ///AS
        ///-- =============================================
        ///-- Author         : {AUTHOR_NAME}
        ///-- Creation Date  : {CREATION_DATE}
        ///-- Main Entity    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sp_GetByID {
            get {
                return ResourceManager.GetString("sp_GetByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINT N&apos;Stored Procedure [dbo].[{LISTALL_STORED_PROCEDURE}]&apos;
        ///GO
        ///IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[{LISTALL_STORED_PROCEDURE}]&apos;) AND TYPE IN (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[{LISTALL_STORED_PROCEDURE}]  
        ///GO
        ///CREATE PROCEDURE [dbo].[{LISTALL_STORED_PROCEDURE}]
        ///AS
        ///-- =============================================
        ///-- Author         : {AUTHOR_NAME}
        ///-- Creation Date  : {CREATION_DATE}
        ///-- Main Entity    : {ENTITY_NAME}
        ///-- Description    : List All Entities from  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sp_ListAll {
            get {
                return ResourceManager.GetString("sp_ListAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINT N&apos;Stored Procedure [dbo].[{SAVE_STORED_PROCEDURE}]&apos;
        ///GO
        ///IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[{SAVE_STORED_PROCEDURE}]&apos;) AND TYPE IN (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[{SAVE_STORED_PROCEDURE}]  
        ///GO
        ///CREATE PROCEDURE [dbo].[{SAVE_STORED_PROCEDURE}]
        ///(/*-- BEGIN SECTION PARAMETERS */
        ///    /*-- BEGIN SECTION DEFAULT AS VAR */
        ///   @{VAR.PARAMETERNAME} {VAR.DATATYPE}/*-- END SECTION DEFAULT */
        ///    /*-- END SECTION PARAMETERS */
        ///)
        ///AS
        ///-- ========================== [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sp_Save {
            get {
                return ResourceManager.GetString("sp_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string view_Create {
            get {
                return ResourceManager.GetString("view_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string view_Delete {
            get {
                return ResourceManager.GetString("view_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string view_Details {
            get {
                return ResourceManager.GetString("view_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string view_Edit {
            get {
                return ResourceManager.GetString("view_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string view_Index {
            get {
                return ResourceManager.GetString("view_Index", resourceCulture);
            }
        }
    }
}
